repos:
-   repo: local
    hooks:
    -   id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        files: ^(src|tests|evaluation|scripts).*\.py$
        exclude: |
            (?x)^(
                src/fandango/language/parser/FandangoLexer.py|
                src/fandango/language/parser/sa_fandango\.py|
                src/fandango/language/parser/.*Parser.*\.py|
                src/fandango/converters/antlr/ANTLRv4.*\.py
            )$
-   repo: local
    hooks:
    -   id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: system
        files: ^(src|tests|evaluation|scripts).*\.py$
        exclude: |
            (?x)^(
                src/fandango/language/parser/FandangoLexer.py|
                src/fandango/language/parser/sa_fandango\.py|
                src/fandango/language/parser/.*Parser.*\.py|
                src/fandango/converters/antlr/ANTLRv4.*\.py
            )$
-   repo: local
    hooks:
    -   id: mypy
        name: mypy (non-strict)
        entry: mypy
        language: python
        files: ^(tests|evaluation|scripts).*\.py$
        exclude: |
            (?x)^(
                src/fandango/language/parser/FandangoLexer.py|
                src/fandango/language/parser/sa_fandango\.py|
                src/fandango/language/parser/.*Parser.*\.py|
                src/fandango/converters/antlr/ANTLRv4.*\.py|
                evaluation/protocol_testing_eval/profuzzbench/.*
            )$
    -   id: mypy-strict
        name: mypy (strict for src/)
        entry: mypy
        language: python
        args:
        - --strict
        files: ^src/.*\.py$
        exclude: |
            (?x)^(
                src/fandango/language/parser/FandangoLexer.py|
                src/fandango/language/parser/sa_fandango\.py|
                src/fandango/language/parser/.*Parser.*\.py|
                src/fandango/converters/antlr/ANTLRv4.*\.py|
                evaluation/protocol_testing_eval/profuzzbench/.*
            )$
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.11.7 # Correspond to uv version
  hooks:
    - id: uv-lock
    - id: uv-export
      args: ["--output-file=pylock.toml", "--all-extras", "--locked"]
