title: Fuzzing with Fandango
author: José Antonio Zamudio Amaya, Valentin Huber, Alexander Liggesmeyer, Marius Smytzek, and Andreas Zeller
logo: fandango.png
copyright: 2024-2026 CISPA Helmholtz Center for Information Security (www.cispa.de). All Rights Reserved.
exclude_patterns: [BookIntro.md]

bibtex_bibfiles:
    - fandango.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    bibtex_bibfiles: "fandango.bib"

latex:
  latex_documents:
     targetname: fandango.tex

sphinx:
  config:
    latex_engine: xelatex
    latex_show_pagerefs: true
    latex_show_urls: footnote
  extra_extensions:
    - sphinxcontrib.mermaid


execute:
  execute_notebooks: cache
  stderr_output: error
  timeout: 300

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
    - deflist

html:
  use_issues_button: true
  use_repository_button: true
  announcement: "<a href=\"https://pypi.org/project/fandango-fuzzer/1.1.1/\" style=\"color:white;\">Fandango 1.1.1</a> is now available! Check out the <a href=\"https://fandango-fuzzer.github.io/ReleaseNotes.html#\" style=\"color:white;\">release notes</a> for details."

repository:
  url: "https://github.com/fandango-fuzzer/fandango"